name: Release Targets

on:
  create:
    tags:
      - .*

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - run: npm install
    - run: npm run build --if-present
    - name: Zip manifest.json
      run: |
        zip --junk-paths nextcloud.zip ../plugin-assets/manifest.json ../plugin-assets/color.png ../plugin-assets/outline.png
    - name: Zip Release Build
      run: |
        zip dist.zip ./dist/*/**
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true
        prerelease: false
    - name: Upload Manifest
      id: upload_manifest
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./frontend/nextcloud.zip
        asset_name: nextcloud.zip
        asset_content_type: application/zip
    - name: Upload dist
      id: upload_dist
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
       upload_url: ${{ steps.create_release.outputs.upload_url }}
       asset_path: ./frontend/dist.zip
       asset_name: release-code.zip
       asset_content_type: application/zip


